# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5007103d8b214bd0233ab7c47bfad123e43f4f06373da7c013c2dcffbbd829537bebfa61c06dfb572abf3c8e793c4374022bbe7d6d370e62c2074d03842b9ef0

test:
  secret_key_base: b12e7e563808c6bca06ce4065eb5ca77591df3e7a746fc1fb096f6031a19e2ac1dad2c1718f42c389da0458340f827b8589b1138a04490ac07f4ef05b55a98eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
